listen_addresses = ['127.0.0.1:5053']
server_names = ['cloudflare', 'cloudflare-ipv6']
require_dnssec = true
doh_servers = true
dnscrypt_servers = false

[sources.public-resolvers]
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  cache_file = '/tmp/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
